services:
  zinalog:
    image: ghcr.io/iamceeso/zinalog:latest
    container_name: zinalog
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      PORT: "4000"
      HOSTNAME: "0.0.0.0"
      DATABASE_PATH: /data/logs.db
      TRUST_PROXY: "false"
    volumes:
      - zinalog-data:/data

volumes:
  zinalog-data:
